### ISSUE TITLE
Three person chess board

### ISSUE THREAD

**Issue by apfohl** [ovgu-ccd/jchess#21]
Think about a layout for the board as well as movement rules on this board. Because of the more complex structure, a simple array to represent the board is not sufficient anymore. Figure out a new data structure. Create a rough software design based on your decisions.

**Note:** we recommend using UML to create your software design. It allows you to easily share your ideas and gives you a quick overview about your system.

* [x] chess board
* [x] start configuration
* [x] data structure
* [x] implementaion

**Comment by rheum** [comment]
It works nicely, however I have one suggestion:

Could we also use the blue channel to store whether or not a pixel is actually on the board?
This would mean that all pixels outside of the board should have a blue value of 0. The absolute ids could simply start with 1 instead of zero.

**Comment by ParticlePeter** [comment]
I do understand your problem, but I do not like your sollution suggestion. As a mater of fact I see that the png is a RGBA texture, the alpha channel should be 255 on the board and 0 anywhere else already. But just in case you cannot access the alpha channel I'l fill the BG in a white color.With this approach all the tile IDs stay the same, and you need to compare any color value against 255. Is that O.K. with you ?

**Comment by ParticlePeter** [comment]
![tilepicker](https://cloud.githubusercontent.com/assets/1482313/5660360/aa2df306-971f-11e4-8527-56d3b3ee6d0a.png)

**Comment by rheum** [comment]
Brilliant ;)

**Comment by ParticlePeter** [comment]
New Board Texture and Tile Pickers, based on hexagonal grid coordinates based on following Article:
http://www.redblobgames.com/grids/hexagons/
To iterate over each Tile, only Board only axial coordinates can be used currently, with this function (use both the loops to reach each of the tiles ):

[code]
	for( a = 0 ; a < 8 ; ++a )  {
		for( b = 0 ; b < ( 8 + a ) ; ++b )  {
			Tile tile = board.getTile( CoordinateConverter.boardAxialCoordinateToIndex( a , b ));
			// tile.doSomething() ;
		}
	}

	for( a = 8 ; a < 15 ; ++a )  {
		$g = a - 9 ;
		for( b = $g + 2 ; b < 15 ; ++b )  {
			Tile tile = board.getTile( CoordinateConverter.boardAxialCoordinateToIndex( a , b ));
			// tile.doSomething() ;
		}
	}
[/code]

**Comment by ParticlePeter** [comment]
New Board:
![board](https://cloud.githubusercontent.com/assets/1482313/5696879/eae11104-99df-11e4-8f42-85c48c4289d0.png)

**Comment by ParticlePeter** [comment]
New TilePicker:
![tilepicker](https://cloud.githubusercontent.com/assets/1482313/5696882/0151d45a-99e0-11e4-823d-ba64d8183858.png)

**Comment by ParticlePeter** [comment]
TileHighliter to display possible moves
![tilehighliter](https://cloud.githubusercontent.com/assets/1482313/5697201/baaed6dc-99ea-11e4-95cb-e328d1dac4de.png)

**Comment by apfohl** [comment]
We are done with this one right?

**Comment by apfohl** [comment]
New changes should be done in new issues.
