### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by apfohl** [ovgu-ccd/jchess#24]
Use Log4J ([http://logging.apache.org/log4j/1.2/](http://logging.apache.org/log4j/1.2/)) to log all Console outputs in a log file. Create two separated logfiles for logging all events and only errors. Replace all “System.out.println” commands within the JavaOpenChess project by log4j messages.

**Note:** to still get messages in your console, you can additionally pipe your log messages to the console output.

**Comment by svrin** [comment]
Has been decided to be in use and is used in implementation
