### ISSUE TITLE
Promotion of an pawn

### ISSUE THREAD

**Issue by apfohl** [ovgu-ccd/jchess#26]
By now, the promotion of a pawn figure that reaches the other end of the game board is not implemented in javaOpenChess. Implement this functionality. Document your software design and give arguments, why you chose inheritance, interface, composition etc. Check this documentation in adequate form into the version control system.

**Note:** Basically the pawn has to be capable of all possible movements of a queen. Think a little bit ahead for 3-person chess (e.g. some figure is transformed into a “Great Empress” by “Old Woman” after sucking out the poison of the “Serpent”). Re-consider the principle/patterns you learned, when designing the solution.

**Comment by svrin** [comment]
Resolved in branch by @apfohl
