### ISSUE TITLE
Test automation

### ISSUE THREAD

**Issue by apfohl** [ovgu-ccd/jchess#28]
Configure Jenkins to automatically execute all unit tests after your Jenkins server build a new version. To check the code coverage of your tests, add Cobertura to your build server ([https://wiki.jenkins- ci.org/display/JENKINS/Cobertura+Plugin](https://wiki.jenkins- ci.org/display/JENKINS/Cobertura+Plugin)). Therefore you have to extend your ANT script to run Cobertura.

**Comment by svrin** [comment]
Automation is done in jenkins and travis
