### ISSUE TITLE
Test Driven Development

### ISSUE THREAD

**Issue by apfohl** [ovgu-ccd/jchess#29]
Continue with your 3-person chess project. This should include the implementation of the chessboard data structure as well as the implementation of corresponding movement rules for the figures. To do so, use something similar to test driven development approach. In other words, create the class body including member variables and functions. Then create the according unit tests that will test the correct behavior of your methods. This explicitly includes testing of unwanted behavior like unwanted return values etc. Check-In your test and afterwards start implementing the methods while checking, if your method works as expected.

**Note:** It is not necessary to follow this approach for every single class. Choose the main entry points of the component you want to implement and test the correct behavior of this functionality, implying that these methods only work if all underlying methods work correctly. Be aware that this approach is only as good as the test you wrote in the beginning. This method works best, if you write a test which is implemented by your team member.

**Comment by svrin** [comment]
Will be done by an eat a frog per day run :)
