### ISSUE TITLE
Eat a frog per day: Write Test

### ISSUE THREAD

**Issue by svrin** [ovgu-ccd/jchess#67]
Write a test per day :)

 * Freitag 16.01
    * [x] @apfohl 
    * [ ] @rheum 
    * [ ] @ParticlePeter 
    * [ ] @svrin
 * Samstag 17.01
    * [x] @apfohl 
    * [ ] @rheum 
    * [ ] @ParticlePeter 
    * [ ] @svrin
 * Sonntag 18.01
    * [x] @apfohl 
    * [ ] @rheum 
    * [ ] @ParticlePeter 
    * [ ] @svrin
 * Montag 19.01
    * [x] @apfohl 
    * [ ] @rheum 
    * [ ] @ParticlePeter 
    * [ ] @svrin
 * Dienstag 20.01
    * [x] @apfohl 
    * [ ] @rheum 
    * [ ] @ParticlePeter 
    * [ ] @svrin

**Comment by apfohl** [comment]
This is nonsense.
